<?php
$title = 'My solmization strings';
$this->headTitle($title);
?>
<div id="head">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <div id="login">
        <?php
        $user = $this->identity();
        if ($user) {
            echo '<div id="logged-in-message">Logged in as ' . $this->escapeHtml($user->getUsername()) . '</div>';
            echo '<form action="&#x2F;solmik&#x2F;logout" method="POST" name="login-form" id="logout-form"><input name="submit" type="submit" value="Log out"></form>';
        } else {
            $loginForm->prepare();
            $loginForm->setAttribute('action', $this->url(
                            'solmik', array(
                        'action' => 'login'
                            )
            ));
            echo $this->form()->openTag($loginForm);
            echo $this->formCollection($loginForm);
            echo $this->form()->closeTag();
        }
        ?>
    </div>
</div>
<div id="upper">
    <div id="upper1">
        <div id="div1">
            <div id="all-squares">
                <div id="sq11" class="squares-3x3">
                    <div class="row">
                        <div></div><div></div><div></div>
                    </div>
                    <div class="row">
                        <div></div><div></div><div></div>
                    </div>
                    <div class="row">
                        <div></div><div></div><div></div>
                    </div>
                </div>
                <div id="sq10" class="squares-3x3">
                    <div class="row">
                        <div></div><div></div><div></div>
                    </div>
                    <div class="row">
                        <div></div><div></div><div></div>
                    </div>
                    <div class="row">
                        <div></div><div></div><div></div>
                    </div>
                </div>
                <div id="sq9" class="squares-3x3">
                    <div class="row">
                        <div></div><div></div><div></div>
                    </div>
                    <div class="row">
                        <div></div><div></div><div></div>
                    </div>
                    <div class="row">
                        <div></div><div></div><div></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="upper2">
        <div id="staff"><img src="/module/solmik/images/staff.svg" alt="staff"></div>
        <div id="message-staff"></div>
        <div class="used-string"></div>
        <div class="notes-string"></div>
        <div class="frequencies-string"></div>
        <div id="frequencies-string2"></div>
    </div>
</div>
<p class="categories-top">
    <strong>Categories</strong>
    <?php if ($user) : ?>
        - <a href="<?php
//    echo $this->url('solmik', array('controller' => 'solmik-category', 'action' => 'create')); 
        echo $this->url('solmik-category', array('action' => 'create'));
        ?>">Add new Category</a>
         <?php endif ?>
</p>
<table class="table" id="solmi-strings">
    <?php foreach ($categories as $cKey => $category) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($category->getName()); ?>
                <?php if ($user) : ?>
                    <a href="<?php echo $this->url('solmik-category', array('action' => 'edit', 'id' => $category->getId()));
                    ?>">Edit</a> - 
                    <a href="<?php echo $this->url('solmik-category', array('action' => 'delete', 'id' => $category->getId()));
                    ?>">Delete</a> - 
                    <a href="<?php echo $this->url('solmik-string', array('action' => 'create', 'id' => $category->getId()));
                    ?>">Add string</a>
                   <?php endif ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php if ($stringForms[$cKey]): ?> 
                    <ul>
                        <?php
                        $solmistrings = $category->getSolmistrings();
                        for ($j = 0; $j < count($stringForms[$cKey]); $j++) :
                            ?> 
                            <li><?php
                                $stringForm = $stringForms[$cKey][$j];
//                                $stringForm->setAttribute('action', $this->url(
//                                                'solmik-string', array(
//                                            'action' => 'edit',
//                                            'id' => $this->id,
//                                                )
//                                ));
                                $stringForm->prepare();

                                echo $this->form()->openTag($stringForm);
                                echo $this->formCollection($stringForm);
                                echo $this->form()->closeTag();
                                ?> 
                                <?php if ($user) : ?>
                                    <a href="<?php echo $this->url('solmik-string', array('action' => 'edit', 'id' => $solmistrings[$j]->getId())); ?>">Edit</a> - 
                                    <a href="<?php echo $this->url('solmik-string', array('action' => 'delete', 'id' => $solmistrings[$j]->getId())); ?>">Delete</a>
                                    - <?php endif ?>
                                <?php echo $solmistrings[$j]->getName(); ?>
                            </li>
                        <?php endfor; ?> 
                    </ul>
                <?php endif; ?> 
            </td>
        </tr>
    <?php endforeach; ?>
</table>